# Generated by Django 5.1.7 on 2025-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
